# Generated by Django 2.2.6 on 2019-10-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0003_auto_20191016_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='received_date',
            new_name='income_date',
        ),
    ]
