# Generated by Django 2.2.6 on 2019-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0004_auto_20191016_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='planned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='planned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
